<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="goalmodel"
    nsURI="goalmodel.ecore" nsPrefix="it.unitn.disi.awreqs.model">
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="LTL.ecore#//OclAny">
    <eOperations name="now" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eOperations name="cal" eType="#//Calendar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecidableRequirement" eSuperTypes="#//Requirement">
    <eOperations name="start"/>
    <eOperations name="end"/>
    <eOperations name="success"/>
    <eOperations name="fail"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Softgoal" eSuperTypes="#//Requirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="approximatedQualityConstraints"
        upperBound="-1" eType="#//QualityConstraint" eOpposite="#//QualityConstraint/approximatedSoftgoals"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AwReq" eSuperTypes="#//DecidableRequirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredRequirements" upperBound="-1"
        eType="#//DecidableRequirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildRequirement" eSuperTypes="#//DecidableRequirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentDecomposition" eType="#//Decomposition"
        eOpposite="#//Decomposition/childRequirements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualityConstraint" eSuperTypes="#//DecidableRequirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="approximatedSoftgoals"
        upperBound="-1" eType="#//Softgoal" eOpposite="#//Softgoal/approximatedQualityConstraints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedRequirements"
        upperBound="-1" eType="#//LongRunningRequirement" eOpposite="#//LongRunningRequirement/associatedQualityConstraints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LongRunningRequirement" eSuperTypes="#//ChildRequirement">
    <eOperations name="cancel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedQualityConstraints"
        upperBound="-1" eType="#//QualityConstraint" eOpposite="#//QualityConstraint/associatedRequirements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainAssumption" eSuperTypes="#//ChildRequirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//LongRunningRequirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposition" lowerBound="1"
        eType="#//Decomposition" eOpposite="#//Decomposition/goal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//LongRunningRequirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Decomposition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="goal" lowerBound="1" eType="#//Goal"
        eOpposite="#//Goal/decomposition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childRequirements" lowerBound="1"
        upperBound="-1" eType="#//ChildRequirement" containment="true" eOpposite="#//ChildRequirement/parentDecomposition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndDecomposition" eSuperTypes="#//Decomposition"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrDecomposition" eSuperTypes="#//Decomposition"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Calendar" instanceClassName="java.util.Calendar"/>
</ecore:EPackage>
